# На сервере:
# 1. ssh-keygen
# 2. Копировать приватный ключ, положить в переменную PRODUCTION_PRIVATE_KEY в gitlab
# 3. Копировать публичный ключ (~/.ssh/<KEY_NAME>.pub), добавить в ~/.ssh/authorized_keys на сервере
# 4. (prod only) Добавить публичный ключ (~/.ssh/<KEY_NAME>.pub) в SSH-ключи студийного гитлаба
# 5. Добавить в переменную SSH_KNOWN_HOSTS в gitlab (ssh-keyscan -H <SERVER IP>)
# 6. Клонировать репозиторий проекта на удаленный сервер (этот путь будет $PROJECT_PATH)

include:
  - local: ci/_variables.yml
  - local: ci/_hidden_jobs.yml
  - local: ci/frontend_premerge_checks.yml
  - local: ci/frontend_build.yml
  - local: ci/frontend_build_storybook.yml
  - local: ci/frontend_test_storybook.yml
  - local: ci/frontend_deploy.yml
  - local: ci/frontend_deploy_storybook.yml
  - local: ci/pull.yml

image: alpine

stages:
  - build
  - test
  - deploy
  - deploy_after
